###############################################################################
# Introduction:
# -------------
# This workflow builds the NMDC documentation, checks for broken links, 
# and identifies any spelling errors in the documentation.
# If any issues are found (broken links or misspelled words), it creates
# GitHub Issues containing lists of the errors for further review and fixing.
#
###############################################################################



name: Check Links and Spelling

on:
  push: { branches: [ 60-add-spell-checker ] }
  workflow_dispatch: { }
  workflow_call: { }

jobs:
  # Use existing workflows to compile the legacy documentation.
  # Reference: https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
  build:
    name: Compile main website
    uses: ./.github/workflows/compile-main-website.yml
 
  check-docs:
    name: Check Links and Spelling in Documentation
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # ------------------ Spell Checking ------------------
      - name: Run Spell Checker
        id: spellcheck
        uses: wow-actions/spell-checker@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          include: |
            _build/html/**/*.md
            _build/html/**/*.txt
            _build/html/**/*.html

      - name: Create GitHub Issue for Misspellings
        if: ${{ steps.spellcheck.outputs.found_errors == 'true' }}
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Documentation contains misspelled words
          content-filepath: './spellcheck_report.txt'
          labels: documentation, spelling-error


      # ------------------ Link Checking ------------------
      - name: Hyperlink link checker
        uses: untitaker/hyperlink@0.1.43
        id: linkcheck
        with:
          args: _build/html/ --check-anchors 
          
      - name: Create GitHub Issue listing broken links
        if: ${{ success() && steps.linkcheck.outputs.broken-links != '' }}
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Documentation contains broken links
          content-filepath: './linkcheck_report.txt'
          labels: documentation, broken-link

      