###############################################################################
# Introduction:
# -------------
# This workflow builds the NMDC documentation, checks for broken links, 
# and identifies any spelling errors in the documentation.
# If any issues are found (broken links or misspelled words), it creates
# GitHub Issues containing lists of the errors for further review and fixing.
#
###############################################################################



name: Check Links and Spelling

on:
  push: { branches: [ 61-add-link-checker ] }
  workflow_dispatch: { }
  workflow_call: { }

jobs:
  check-links:
    name: Check Links in Documentation
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out commit  
        uses: actions/checkout@v4
      - name: Download all artifacts
        uses: actions/download-artifact@v4 
        with:
          path: artifacts
      - name: Run Markdown Link Check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        id: linkcheck
        continue-on-error: true
        with:
          use-quiet-mode: yes
          use-verbose-mode: no
          folder-path: 'artifacts/'
          max-depth: -1
          file-extension: .html
          base-branch: main
          output: linkcheck_output.txt
      - name: Save Link Check Output
        run: |
          mkdir -p linkcheck_reports 
          echo "${{ steps.linkcheck.outputs.result }}" > linkcheck_reports/linkcheck_output.txt
          ls 
          ls linkcheck_reports
      - name: Create GitHub Issue for Broken Links
        if: ${{ steps.linkcheck.outcome != 'success' }}
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Broken links detected in documentation
          content-filepath: linkcheck_reports/linkcheck_output.txt
          labels: documentation, broken-link

      # ------------------ Spell Checking ------------------
  check-spelling:
    name: Check Spelling in Documentation
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out commit  # Docs: https://github.com/actions/checkout
        uses: actions/checkout@v4
      - name: Download all artifacts
        uses: actions/download-artifact@v4  # Docs: https://github.com/actions/download-artifact
        with:
          path: artifacts
      - name: Run Spell Checker
        id: spellchecker-cli
        continue-on-error: true
        run: |
          mkdir -p spellcheck_reports
          npx -y spellchecker-cli --files artifacts/**/*.html \
            --dictionaries .github/workflows/dictionary.txt \
            --plugins spell indefinite-article repeated-words syntax-mentions syntax-urls \
            --reports spellcheck_reports/spellcheck_report.json \
            > spellcheck_reports/spellcheck_output.txt
          ls
          ls spellcheck_reports/
      # - name: Upload Spell Check Artifacts
      #   uses: actions/upload-artifact@v3
      #   if: ${{ steps.spellchecker-cli.outcome == 'success' }}
      #   with:
      #     path: spellcheck_reports
      - name: Create GitHub Issue for Misspellings
        if: ${{ steps.spellchecker-cli.outcome == 'success' }}
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Documentation contains misspelled words
          content-filepath: spellcheck_reports/spellcheck_output.txt
          labels: documentation, spelling-error

     