name: Check Spelling

on:
  push: { branches: [ main ] }
  workflow_dispatch: { }
  workflow_call: { }

jobs:
  check-spelling:
    name: Check Spelling in Documentation
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out commit  # Docs: https://github.com/actions/checkout
        uses: actions/checkout@v4
      - name: Download all artifacts
        uses: actions/download-artifact@v4  # Docs: https://github.com/actions/download-artifact
        with:
          path: artifacts
      - name: Run Spell Checker
        id: spellchecker-cli
        continue-on-error: true
        run: |
          mkdir -p spellcheck_reports
          npx -y spellchecker-cli --files artifacts/**/*.html \
            --dictionaries .github/workflows/dictionary.txt \
            --plugins spell indefinite-article repeated-words syntax-mentions syntax-urls \
            --reports spellcheck_reports/spellcheck_report.json \
            > spellcheck_reports/spellcheck_output.txt
          ls
          ls spellcheck_reports/
      # - name: Upload Spell Check Artifacts
      #   uses: actions/upload-artifact@v3
      #   if: ${{ steps.spellchecker-cli.outcome == 'success' }}
      #   with:
      #     path: spellcheck_reports
      - name: Create GitHub Issue for Misspellings
        if: ${{ steps.spellchecker-cli.outcome == 'success' }}
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Documentation contains misspelled words
          content-filepath: spellcheck_reports/spellcheck_output.txt
          labels: documentation, spelling-error