###############################################################################
# Introduction:
# -------------
# This workflow builds the NMDC documentation, checks for broken links,
# and identifies any spelling errors in the documentation.
# If any issues are found (broken links or misspelled words), it creates
# GitHub Issues containing lists of the errors for further review and fixing.
#
###############################################################################

name: Check Links and Spelling in Documentation

on:
  push: { branches: [ main ] }
  workflow_dispatch: { }
  workflow_call: { }
  pull_request: {}

jobs:
  check-links:
    name: Check Links in Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Check out commit
        uses: actions/checkout@v4
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Run Markdown Link Check
        id: linkcheck
        # Source: https://github.com/tcort/markdown-link-check
        continue-on-error: true
        run: |
          mkdir -p linkcheck_reports
          npx markdown-link-check \
            --quiet \
            --verbose \
            artifacts/**/*.html |
           tee linkcheck_reports/linkcheck_output.txt
          # if grep -q 'Error' linkcheck_reports/linkcheck_output.txt; then
          #   echo "links_broken=true" >> $GITHUB_ENV
          # else
          #   echo "links_broken=false" >> $GITHUB_ENV
          # fi

      - name: Create GitHub Issue for Broken Links
        if: ${{ steps.linkcheck.outcome != 'success' }}
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Broken links detected in documentation
          content-filepath: linkcheck_reports/linkcheck_output.txt
          labels: documentation, broken-link

  check-spelling:
    name: Check Spelling in Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Check out commit
        uses: actions/checkout@v4
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Run Spell Checker
        id: spellcheck
        continue-on-error: true
        # Source: https://github.com/tbroadley/spellchecker-cli and https://github.com/austenstone/spellchecker-cli-action-summary
        # Based off: https://github.com/austenstone/spellchecker-cli-action-summary/blob/main/.github/workflows/spellcheck.yml
        run: |
          mkdir -p spellcheck_reports
          npx -y spellchecker-cli \
            --files artifacts/**/*.html \
            --dictionaries .github/workflows/spellcheck_allow_list.txt \
            --plugins spell indefinite-article repeated-words syntax-mentions syntax-urls \
            --reports spellcheck_reports/spellcheck_report.json
          # if grep -q 'misspelt' spellcheck_reports/spellcheck_report.json; then
          #   echo "misspelt=true" >> $GITHUB_OUTPUT
          # else
          #   echo "misspelt=false" >> $GITHUB_OUTPUT
          # fi

      - name: Create GitHub Issue for Misspellings
        if: ${{ steps.spellcheck.outcome != 'success' }}
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Documentation contains misspelled words
          content-filepath: spellcheck_reports/spellcheck_report.json
          labels: documentation, spelling-error